### ISSUE TITLE
search results - explore the collections

### ISSUE THREAD

**Issue by roxannewyns** [libis/Husserl-Omeka#11]
In de resultaten van explore collection komt ook News voor. Ik zou die daaruit willen laten. Optie is om items van het type News aan collectie News te hangen, en deze uit te sluiten van indexering. Maar dan vind je deze items natuurlijk ook niet meer terug via de algemene search. Op zich lijkt me dat geen ramp, maar misschien zijn er andere optie (zo'n lange sorl query met alle types in lijkt me ook niet ideaal)?

![image](https://user-images.githubusercontent.com/3798589/38077247-a9385410-3338-11e8-89e4-0645e4761eb2.png)

**Comment by JorisLambrechts** [comment]
De andere optie is dat we voor news sql search gebruiken i.p.v solr. Dan moeten we een één nieuwe template maken zoals bijv. bij kadoc. Je krijgt dan een url zoals /search?query=test&query_type=keyword&type=News. 

Het probleem hiermee is dat je als je de url aanpast hier ook alle items te zien krijgt en dus met 2 zoeksystemen langs elkaar zit.

We kunnen ook een shortcode gebruiken op een simple page om alle voorgaande nieuwsberichten te tonen, dat is misschien nog de beste optie. Dan is er wel geen zoekmogelijkheid voor nieuws.

**Comment by roxannewyns** [comment]
lijkt me niet echt nodig om een zoekoptie voor nieuws te hebben. Doe maar zo als dat eenvoudigste is.
