### ISSUE TITLE
afbeeldingen op home page

### ISSUE THREAD

**Issue by roxannewyns** [libis/Husserl-Omeka#7]
kan je het zo aanpassen dat ik voor elk blokje een andere afbeelding kan toevoegen.

![image](https://user-images.githubusercontent.com/3798589/38073552-dfe274e4-332b-11e8-84b5-90cda09c23fb.png)

**Comment by JorisLambrechts** [comment]
Er is nu een bg1.png, bg2.png, bg3.png en bg4.png in /images (niet in ph). Bij de volgende deployment worden deze getoond.
