### ISSUE TITLE
Home page -  spotlight en news

### ISSUE THREAD

**Issue by roxannewyns** [libis/Husserl-Omeka#8]
Wat komt er onder Spotlight? Zijn dat featured items (elk item type: titel en beschrijvingsveld)? Moet nog geïmplementeerd worden.

Hetzelfde voor nieuws. Ik heb een ietem van itemtype nieuws aangemaakt.

**Comment by JorisLambrechts** [comment]
Spotlight zijn inderdaad featured items. Is dat nog nodig of mag dat weg?

**Comment by roxannewyns** [comment]
Laat maar met deze setting staan. Allen denk ik niet dat als je nu een item op featured zet, deze daar verschijnen.
